const nodeInput = ({ $body, $headers, $env, $data }) => {
  return {
    BUILDABLE_STRIPE_SECRET_KEY: $env.BUILDABLE_STRIPE_SECRET_KEY, // Required

    // address: {
    //     city: "string",
    //     country: "string",
    //     line1: "string",
    //     line2: "string",
    //     postal_code: "string",
    //     state: "string"
    //   },
    // balance: "<integer>",
    // cash_balance: { settings: { reconciliation_mode: "automatic" } },
    // coupon: "<string>",
    // description: "<string>",
    // email: "<string>",
    // expand: ["string"],
    // invoice_prefix: "<string>",
    // invoice_settings: {
    //     custom_fields: [{ name: "string", value: "string" }],
    //     default_payment_method: "string",
    //     footer: "string",
    //     rendering_options: { amount_tax_display: "" }
    //   },
    // metadata: { property1: "string", property2: "string" },
    // name: "<string>",
    // next_invoice_sequence: "<integer>",
    // payment_method: "<string>",
    // phone: "<string>",
    // preferred_locales: ["string"],
    // promotion_code: "<string>",
    // shipping: {
    //     address: {
    //       city: "string",
    //       country: "string",
    //       line1: "string",
    //       line2: "string",
    //       postal_code: "string",
    //       state: "string"
    //     },
    //     name: "string",
    //     phone: "string"
    //   },
    // source: "<string>",
    // tax: { ip_address: "string" },
    // tax_exempt: "<string>",
    // tax_id_data: [{ type: "ae_trn", value: "string" }],
    // test_clock: "<string>",
    // addressCity: "<string>",
    // addressCountry: "<string>",
    // addressLine1: "<string>",
    // addressLine2: "<string>",
    // addressPostal_code: "<string>",
    // addressState: "<string>",
    // cash_balanceSettingsReconciliation_mode: "<string>",
    // expand0: "<string>",
    // expand1: "<string>",
    // invoice_settingsCustom_fields0Name: "<string>",
    // invoice_settingsCustom_fields0Value: "<string>",
    // invoice_settingsCustom_fields1Name: "<string>",
    // invoice_settingsCustom_fields1Value: "<string>",
    // invoice_settingsDefault_payment_method: "<string>",
    // invoice_settingsFooter: "<string>",
    // invoice_settingsRendering_optionsAmount_tax_display: "<string>",
    // preferred_locales0: "<string>",
    // preferred_locales1: "<string>",
    // shippingAddressCity: "<string>",
    // shippingAddressCountry: "<string>",
    // shippingAddressLine1: "<string>",
    // shippingAddressLine2: "<string>",
    // shippingAddressPostal_code: "<string>",
    // shippingAddressState: "<string>",
    // shippingName: "<string>",
    // shippingPhone: "<string>",
    // taxIp_address: "<string>",
    // tax_id_data0Type: "<string>",
    // tax_id_data0Value: "<string>",
    // tax_id_data1Type: "<string>",
    // tax_id_data1Value: "<string>",
  };
};
