const nodeInput = ({ $body, $headers, $env, $data }) => {
  return {
    BUILDABLE_STRIPE_SECRET_KEY: $env.BUILDABLE_STRIPE_SECRET_KEY, // Required

    // bbpos_wisepos_e: { splashscreen: "string" },
    // expand: ["string"],
    // tipping: {
    //     aud: { fixed_amounts: [0], percentages: [0], smart_tip_threshold: 0 },
    //     cad: { fixed_amounts: [0], percentages: [0], smart_tip_threshold: 0 },
    //     chf: { fixed_amounts: [0], percentages: [0], smart_tip_threshold: 0 },
    //     czk: { fixed_amounts: [0], percentages: [0], smart_tip_threshold: 0 },
    //     dkk: { fixed_amounts: [0], percentages: [0], smart_tip_threshold: 0 },
    //     eur: { fixed_amounts: [0], percentages: [0], smart_tip_threshold: 0 },
    //     gbp: { fixed_amounts: [0], percentages: [0], smart_tip_threshold: 0 },
    //     hkd: { fixed_amounts: [0], percentages: [0], smart_tip_threshold: 0 },
    //     myr: { fixed_amounts: [0], percentages: [0], smart_tip_threshold: 0 },
    //     nok: { fixed_amounts: [0], percentages: [0], smart_tip_threshold: 0 },
    //     nzd: { fixed_amounts: [0], percentages: [0], smart_tip_threshold: 0 },
    //     sek: { fixed_amounts: [0], percentages: [0], smart_tip_threshold: 0 },
    //     sgd: { fixed_amounts: [0], percentages: [0], smart_tip_threshold: 0 },
    //     usd: { fixed_amounts: [0], percentages: [0], smart_tip_threshold: 0 }
    //   },
    // verifone_p400: { splashscreen: "string" },
    // bbpos_wisepos_eSplashscreen: "<string>",
    // expand0: "<string>",
    // expand1: "<string>",
    // tippingAudFixed_amounts0: "<integer>",
    // tippingAudFixed_amounts1: "<integer>",
    // tippingAudPercentages0: "<integer>",
    // tippingAudPercentages1: "<integer>",
    // tippingAudSmart_tip_threshold: "<integer>",
    // tippingCadFixed_amounts0: "<integer>",
    // tippingCadFixed_amounts1: "<integer>",
    // tippingCadPercentages0: "<integer>",
    // tippingCadPercentages1: "<integer>",
    // tippingCadSmart_tip_threshold: "<integer>",
    // tippingChfFixed_amounts0: "<integer>",
    // tippingChfFixed_amounts1: "<integer>",
    // tippingChfPercentages0: "<integer>",
    // tippingChfPercentages1: "<integer>",
    // tippingChfSmart_tip_threshold: "<integer>",
    // tippingCzkFixed_amounts0: "<integer>",
    // tippingCzkFixed_amounts1: "<integer>",
    // tippingCzkPercentages0: "<integer>",
    // tippingCzkPercentages1: "<integer>",
    // tippingCzkSmart_tip_threshold: "<integer>",
    // tippingDkkFixed_amounts0: "<integer>",
    // tippingDkkFixed_amounts1: "<integer>",
    // tippingDkkPercentages0: "<integer>",
    // tippingDkkPercentages1: "<integer>",
    // tippingDkkSmart_tip_threshold: "<integer>",
    // tippingEurFixed_amounts0: "<integer>",
    // tippingEurFixed_amounts1: "<integer>",
    // tippingEurPercentages0: "<integer>",
    // tippingEurPercentages1: "<integer>",
    // tippingEurSmart_tip_threshold: "<integer>",
    // tippingGbpFixed_amounts0: "<integer>",
    // tippingGbpFixed_amounts1: "<integer>",
    // tippingGbpPercentages0: "<integer>",
    // tippingGbpPercentages1: "<integer>",
    // tippingGbpSmart_tip_threshold: "<integer>",
    // tippingHkdFixed_amounts0: "<integer>",
    // tippingHkdFixed_amounts1: "<integer>",
    // tippingHkdPercentages0: "<integer>",
    // tippingHkdPercentages1: "<integer>",
    // tippingHkdSmart_tip_threshold: "<integer>",
    // tippingMyrFixed_amounts0: "<integer>",
    // tippingMyrFixed_amounts1: "<integer>",
    // tippingMyrPercentages0: "<integer>",
    // tippingMyrPercentages1: "<integer>",
    // tippingMyrSmart_tip_threshold: "<integer>",
    // tippingNokFixed_amounts0: "<integer>",
    // tippingNokFixed_amounts1: "<integer>",
    // tippingNokPercentages0: "<integer>",
    // tippingNokPercentages1: "<integer>",
    // tippingNokSmart_tip_threshold: "<integer>",
    // tippingNzdFixed_amounts0: "<integer>",
    // tippingNzdFixed_amounts1: "<integer>",
    // tippingNzdPercentages0: "<integer>",
    // tippingNzdPercentages1: "<integer>",
    // tippingNzdSmart_tip_threshold: "<integer>",
    // tippingSekFixed_amounts0: "<integer>",
    // tippingSekFixed_amounts1: "<integer>",
    // tippingSekPercentages0: "<integer>",
    // tippingSekPercentages1: "<integer>",
    // tippingSekSmart_tip_threshold: "<integer>",
    // tippingSgdFixed_amounts0: "<integer>",
    // tippingSgdFixed_amounts1: "<integer>",
    // tippingSgdPercentages0: "<integer>",
    // tippingSgdPercentages1: "<integer>",
    // tippingSgdSmart_tip_threshold: "<integer>",
    // tippingUsdFixed_amounts0: "<integer>",
    // tippingUsdFixed_amounts1: "<integer>",
    // tippingUsdPercentages0: "<integer>",
    // tippingUsdPercentages1: "<integer>",
    // tippingUsdSmart_tip_threshold: "<integer>",
    // verifone_p400Splashscreen: "<string>",
  };
};
