const nodeInput = ({ $body, $headers, $env, $data }) => {
  return {
    BUILDABLE_STRIPE_SECRET_KEY: $env.BUILDABLE_STRIPE_SECRET_KEY, // Required
    currency: "<string>", // Required
    line_items: [
      {
        description: "string",
        discounts: [{ coupon: "string", discount: "string" }],
        price: "string",
        price_data: {
          currency: "string",
          product: "string",
          tax_behavior: "exclusive",
          unit_amount: 0,
          unit_amount_decimal: "string",
        },
        product: "string",
        quantity: 0,
        tax_rates: ["string"],
      },
    ], // Required

    // automatic_tax: { enabled: true },
    // billing_details: {
    //     address: {
    //       city: "string",
    //       country: "string",
    //       line1: "string",
    //       line2: "string",
    //       postal_code: "string",
    //       state: "string"
    //     },
    //     email: "string",
    //     name: "string",
    //     phone: "string"
    //   },
    // customer: "<string>",
    // description: "<string>",
    // discounts: [{ coupon: "string", discount: "string", promotion_code: "string" }],
    // expand: ["string"],
    // ip_address: "<string>",
    // metadata: { property1: "string", property2: "string" },
    // payment: {
    //     settings: {
    //       application_fee_amount: 0,
    //       payment_method_options: {
    //         acss_debit: {
    //           mandate_options: {
    //             custom_mandate_url: "string",
    //             interval_description: "string",
    //             payment_schedule: "combined",
    //             transaction_type: "business"
    //           },
    //           setup_future_usage: "",
    //           verification_method: "automatic"
    //         },
    //         afterpay_clearpay: {
    //           capture_method: "automatic",
    //           reference: "string",
    //           setup_future_usage: "none"
    //         },
    //         alipay: { setup_future_usage: "" },
    //         bancontact: { preferred_language: "de", setup_future_usage: "" },
    //         card: { capture_method: "automatic", setup_future_usage: "none" },
    //         customer_balance: {
    //           bank_transfer: {
    //             eu_bank_transfer: { country: "string" },
    //             requested_address_types: ["iban"],
    //             type: "eu_bank_transfer"
    //           },
    //           funding_type: "bank_transfer",
    //           setup_future_usage: "none"
    //         },
    //         ideal: { setup_future_usage: "" },
    //         klarna: { capture_method: "", preferred_locale: "da-DK", setup_future_usage: "none" },
    //         link: { capture_method: "", persistent_token: "string", setup_future_usage: "" },
    //         oxxo: { expires_after_days: 0, setup_future_usage: "none" },
    //         p24: { setup_future_usage: "none", tos_shown_and_accepted: true },
    //         sepa_debit: { mandate_options: {}, setup_future_usage: "" },
    //         sofort: { preferred_language: "", setup_future_usage: "" },
    //         wechat_pay: { app_id: "string", client: "android", setup_future_usage: "none" }
    //       },
    //       payment_method_types: ["acss_debit"],
    //       return_url: "string",
    //       statement_descriptor: "string",
    //       statement_descriptor_suffix: "string",
    //       transfer_data: { amount: 0, destination: "string" }
    //     }
    //   },
    // shipping_cost: {
    //     shipping_rate: "string",
    //     shipping_rate_data: {
    //       delivery_estimate: {
    //         maximum: { unit: "business_day", value: 0 },
    //         minimum: { unit: "business_day", value: 0 }
    //       },
    //       display_name: "string",
    //       fixed_amount: {
    //         amount: 0,
    //         currency: "string",
    //         currency_options: {
    //           property1: { amount: 0, tax_behavior: "exclusive" },
    //           property2: { amount: 0, tax_behavior: "exclusive" }
    //         }
    //       },
    //       metadata: { property1: "string", property2: "string" },
    //       tax_behavior: "exclusive",
    //       tax_code: "string",
    //       type: "fixed_amount"
    //     }
    //   },
    // shipping_details: {
    //     address: {
    //       city: "string",
    //       country: "string",
    //       line1: "string",
    //       line2: "string",
    //       postal_code: "string",
    //       state: "string"
    //     },
    //     name: "string",
    //     phone: "string"
    //   },
    // tax_details: { tax_exempt: "", tax_ids: [{ type: "ae_trn", value: "string" }] },
    // line_items0Description: "<string>",
    // line_items0Discounts0Coupon: "<string>",
    // line_items0Discounts0Discount: "<string>",
    // line_items0Discounts1Coupon: "<string>",
    // line_items0Discounts1Discount: "<string>",
    // line_items0Price: "<string>",
    // line_items0Price_dataCurrency: "<string>",
    // line_items0Price_dataProduct: "<string>",
    // line_items0Price_dataTax_behavior: "<string>",
    // line_items0Price_dataUnit_amount: "<integer>",
    // line_items0Price_dataUnit_amount_decimal: "<decimal>",
    // line_items0Product: "<string>",
    // line_items0Product_dataId: "<string>",
    // line_items0Product_dataName: "<string>",
    // line_items0Product_dataDescription: "<string>",
    // line_items0Product_dataImages0: "<string>",
    // line_items0Product_dataImages1: "<string>",
    // line_items0Product_dataMetadata: "<object>",
    // line_items0Product_dataPackage_dimensionsHeight: "<number>",
    // line_items0Product_dataPackage_dimensionsLength: "<number>",
    // line_items0Product_dataPackage_dimensionsWeight: "<number>",
    // line_items0Product_dataPackage_dimensionsWidth: "<number>",
    // line_items0Product_dataShippable: "<boolean>",
    // line_items0Product_dataTax_code: "<string>",
    // line_items0Product_dataUrl: "<string>",
    // line_items0Quantity: "<integer>",
    // line_items0Tax_rates0: "<string>",
    // line_items0Tax_rates1: "<string>",
    // line_items1Description: "<string>",
    // line_items1Discounts0Coupon: "<string>",
    // line_items1Discounts0Discount: "<string>",
    // line_items1Discounts1Coupon: "<string>",
    // line_items1Discounts1Discount: "<string>",
    // line_items1Price: "<string>",
    // line_items1Price_dataCurrency: "<string>",
    // line_items1Price_dataProduct: "<string>",
    // line_items1Price_dataTax_behavior: "<string>",
    // line_items1Price_dataUnit_amount: "<integer>",
    // line_items1Price_dataUnit_amount_decimal: "<decimal>",
    // line_items1Product: "<string>",
    // line_items1Product_dataId: "<string>",
    // line_items1Product_dataName: "<string>",
    // line_items1Product_dataDescription: "<string>",
    // line_items1Product_dataImages0: "<string>",
    // line_items1Product_dataImages1: "<string>",
    // line_items1Product_dataMetadata: "<object>",
    // line_items1Product_dataPackage_dimensionsHeight: "<number>",
    // line_items1Product_dataPackage_dimensionsLength: "<number>",
    // line_items1Product_dataPackage_dimensionsWeight: "<number>",
    // line_items1Product_dataPackage_dimensionsWidth: "<number>",
    // line_items1Product_dataShippable: "<boolean>",
    // line_items1Product_dataTax_code: "<string>",
    // line_items1Product_dataUrl: "<string>",
    // line_items1Quantity: "<integer>",
    // line_items1Tax_rates0: "<string>",
    // line_items1Tax_rates1: "<string>",
    // automatic_taxEnabled: "<boolean>",
    // billing_detailsAddressCity: "<string>",
    // billing_detailsAddressCountry: "<string>",
    // billing_detailsAddressLine1: "<string>",
    // billing_detailsAddressLine2: "<string>",
    // billing_detailsAddressPostal_code: "<string>",
    // billing_detailsAddressState: "<string>",
    // billing_detailsEmail: "<string>",
    // billing_detailsName: "<string>",
    // billing_detailsPhone: "<string>",
    // discounts0Coupon: "<string>",
    // discounts0Discount: "<string>",
    // discounts0Promotion_code: "<string>",
    // discounts1Coupon: "<string>",
    // discounts1Discount: "<string>",
    // discounts1Promotion_code: "<string>",
    // expand0: "<string>",
    // expand1: "<string>",
    // paymentSettingsApplication_fee_amount: "<integer>",
    // paymentSettingsPayment_method_optionsAcss_debitMandate_optionsCustom_mandate_url: "<string>",
    // paymentSettingsPayment_method_optionsAcss_debitMandate_optionsInterval_description: "<string>",
    // paymentSettingsPayment_method_optionsAcss_debitMandate_optionsPayment_schedule: "<string>",
    // paymentSettingsPayment_method_optionsAcss_debitMandate_optionsTransaction_type: "<string>",
    // paymentSettingsPayment_method_optionsAcss_debitSetup_future_usage: "<string>",
    // paymentSettingsPayment_method_optionsAcss_debitVerification_method: "<string>",
    // paymentSettingsPayment_method_optionsAfterpay_clearpayCapture_method: "<string>",
    // paymentSettingsPayment_method_optionsAfterpay_clearpayReference: "<string>",
    // paymentSettingsPayment_method_optionsAfterpay_clearpaySetup_future_usage: "<string>",
    // paymentSettingsPayment_method_optionsAlipaySetup_future_usage: "<string>",
    // paymentSettingsPayment_method_optionsBancontactPreferred_language: "<string>",
    // paymentSettingsPayment_method_optionsBancontactSetup_future_usage: "<string>",
    // paymentSettingsPayment_method_optionsCardCapture_method: "<string>",
    // paymentSettingsPayment_method_optionsCardSetup_future_usage: "<string>",
    // paymentSettingsPayment_method_optionsCustomer_balanceBank_transferType: "<string>",
    // paymentSettingsPayment_method_optionsCustomer_balanceBank_transferEu_bank_transferCountry:
    //     "<string>",
    // paymentSettingsPayment_method_optionsCustomer_balanceBank_transferRequested_address_types0:
    //     "<string>",
    // paymentSettingsPayment_method_optionsCustomer_balanceBank_transferRequested_address_types1:
    //     "<string>",
    // paymentSettingsPayment_method_optionsCustomer_balanceFunding_type: "<string>",
    // paymentSettingsPayment_method_optionsCustomer_balanceSetup_future_usage: "<string>",
    // paymentSettingsPayment_method_optionsIdealSetup_future_usage: "<string>",
    // paymentSettingsPayment_method_optionsKlarnaCapture_method: "<string>",
    // paymentSettingsPayment_method_optionsKlarnaPreferred_locale: "<string>",
    // paymentSettingsPayment_method_optionsKlarnaSetup_future_usage: "<string>",
    // paymentSettingsPayment_method_optionsLinkCapture_method: "<string>",
    // paymentSettingsPayment_method_optionsLinkPersistent_token: "<string>",
    // paymentSettingsPayment_method_optionsLinkSetup_future_usage: "<string>",
    // paymentSettingsPayment_method_optionsOxxoExpires_after_days: "<integer>",
    // paymentSettingsPayment_method_optionsOxxoSetup_future_usage: "<string>",
    // paymentSettingsPayment_method_optionsP24Setup_future_usage: "<string>",
    // paymentSettingsPayment_method_optionsP24Tos_shown_and_accepted: "<boolean>",
    // paymentSettingsPayment_method_optionsSepa_debitSetup_future_usage: "<string>",
    // paymentSettingsPayment_method_optionsSofortPreferred_language: "<string>",
    // paymentSettingsPayment_method_optionsSofortSetup_future_usage: "<string>",
    // paymentSettingsPayment_method_optionsWechat_payClient: "<string>",
    // paymentSettingsPayment_method_optionsWechat_payApp_id: "<string>",
    // paymentSettingsPayment_method_optionsWechat_paySetup_future_usage: "<string>",
    // paymentSettingsPayment_method_types0: "<string>",
    // paymentSettingsPayment_method_types1: "<string>",
    // paymentSettingsReturn_url: "<string>",
    // paymentSettingsStatement_descriptor: "<string>",
    // paymentSettingsStatement_descriptor_suffix: "<string>",
    // paymentSettingsTransfer_dataDestination: "<string>",
    // paymentSettingsTransfer_dataAmount: "<integer>",
    // shipping_costShipping_rate: "<string>",
    // shipping_costShipping_rate_dataDisplay_name: "<string>",
    // shipping_costShipping_rate_dataDelivery_estimateMaximumUnit: "<string>",
    // shipping_costShipping_rate_dataDelivery_estimateMaximumValue: "<integer>",
    // shipping_costShipping_rate_dataDelivery_estimateMinimumUnit: "<string>",
    // shipping_costShipping_rate_dataDelivery_estimateMinimumValue: "<integer>",
    // shipping_costShipping_rate_dataFixed_amountAmount: "<integer>",
    // shipping_costShipping_rate_dataFixed_amountCurrency: "<string>",
    // shipping_costShipping_rate_dataFixed_amountCurrency_options: "<object>",
    // shipping_costShipping_rate_dataMetadata: "<object>",
    // shipping_costShipping_rate_dataTax_behavior: "<string>",
    // shipping_costShipping_rate_dataTax_code: "<string>",
    // shipping_costShipping_rate_dataType: "<string>",
    // shipping_detailsAddressCity: "<string>",
    // shipping_detailsAddressCountry: "<string>",
    // shipping_detailsAddressLine1: "<string>",
    // shipping_detailsAddressLine2: "<string>",
    // shipping_detailsAddressPostal_code: "<string>",
    // shipping_detailsAddressState: "<string>",
    // shipping_detailsName: "<string>",
    // shipping_detailsPhone: "<string>",
    // tax_detailsTax_exempt: "<string>",
    // tax_detailsTax_ids0Type: "<string>",
    // tax_detailsTax_ids0Value: "<string>",
    // tax_detailsTax_ids1Type: "<string>",
    // tax_detailsTax_ids1Value: "<string>",
  };
};
