const nodeInput = ({ $body, $headers, $env, $data }) => {
  return {
    BUILDABLE_STRIPE_SECRET_KEY: $env.BUILDABLE_STRIPE_SECRET_KEY, // Required
    customer: "string", // Required

    // address: {
    //     city: "string",
    //     country: "string",
    //     line1: "string",
    //     line2: "string",
    //     postal_code: "string",
    //     state: "string"
    //   },
    // balance: "<integer>",
    // bank_account: {
    //     account_holder_name: "string",
    //     account_holder_type: "company",
    //     account_number: "string",
    //     country: "string",
    //     currency: "string",
    //     object: "bank_account",
    //     routing_number: "string"
    //   },
    // card: {
    //     address_city: "string",
    //     address_country: "string",
    //     address_line1: "string",
    //     address_line2: "string",
    //     address_state: "string",
    //     address_zip: "string",
    //     cvc: "string",
    //     exp_month: 0,
    //     exp_year: 0,
    //     metadata: { property1: "string", property2: "string" },
    //     name: "string",
    //     number: "string",
    //     object: "card"
    //   },
    // cash_balance: { settings: { reconciliation_mode: "automatic" } },
    // coupon: "<string>",
    // default_alipay_account: "<string>",
    // default_bank_account: "<string>",
    // default_card: "<string>",
    // default_source: "<string>",
    // description: "<string>",
    // email: "<string>",
    // expand: ["string"],
    // invoice_prefix: "<string>",
    // invoice_settings: {
    //     custom_fields: [{ name: "string", value: "string" }],
    //     default_payment_method: "string",
    //     footer: "string",
    //     rendering_options: { amount_tax_display: "" }
    //   },
    // metadata: { property1: "string", property2: "string" },
    // name: "<string>",
    // next_invoice_sequence: "<integer>",
    // phone: "<string>",
    // preferred_locales: ["string"],
    // promotion_code: "<string>",
    // shipping: {
    //     address: {
    //       city: "string",
    //       country: "string",
    //       line1: "string",
    //       line2: "string",
    //       postal_code: "string",
    //       state: "string"
    //     },
    //     name: "string",
    //     phone: "string"
    //   },
    // source: "<string>",
    // tax: { ip_address: "string" },
    // tax_exempt: "<string>",
    // trial_end: "now",
    // addressCity: "<string>",
    // addressCountry: "<string>",
    // addressLine1: "<string>",
    // addressLine2: "<string>",
    // addressPostal_code: "<string>",
    // addressState: "<string>",
    // bank_accountAccount_number: "<string>",
    // bank_accountCountry: "<string>",
    // bank_accountAccount_holder_name: "<string>",
    // bank_accountAccount_holder_type: "<string>",
    // bank_accountCurrency: "<string>",
    // bank_accountObject: "<string>",
    // bank_accountRouting_number: "<string>",
    // cardExp_month: "<integer>",
    // cardExp_year: "<integer>",
    // cardNumber: "<string>",
    // cardAddress_city: "<string>",
    // cardAddress_country: "<string>",
    // cardAddress_line1: "<string>",
    // cardAddress_line2: "<string>",
    // cardAddress_state: "<string>",
    // cardAddress_zip: "<string>",
    // cardCvc: "<string>",
    // cardMetadata: "<object>",
    // cardName: "<string>",
    // cardObject: "<string>",
    // cash_balanceSettingsReconciliation_mode: "<string>",
    // expand0: "<string>",
    // expand1: "<string>",
    // invoice_settingsCustom_fields0Name: "<string>",
    // invoice_settingsCustom_fields0Value: "<string>",
    // invoice_settingsCustom_fields1Name: "<string>",
    // invoice_settingsCustom_fields1Value: "<string>",
    // invoice_settingsDefault_payment_method: "<string>",
    // invoice_settingsFooter: "<string>",
    // invoice_settingsRendering_optionsAmount_tax_display: "<string>",
    // preferred_locales0: "<string>",
    // preferred_locales1: "<string>",
    // shippingAddressCity: "<string>",
    // shippingAddressCountry: "<string>",
    // shippingAddressLine1: "<string>",
    // shippingAddressLine2: "<string>",
    // shippingAddressPostal_code: "<string>",
    // shippingAddressState: "<string>",
    // shippingName: "<string>",
    // shippingPhone: "<string>",
    // taxIp_address: "<string>",
  };
};
