const nodeInput = ({ $body, $headers, $env, $data }) => {
  return {
    BUILDABLE_STRIPE_SECRET_KEY: $env.BUILDABLE_STRIPE_SECRET_KEY, // Required

    // account: {
    //     business_type: "company",
    //     company: {
    //       address: {
    //         city: "string",
    //         country: "string",
    //         line1: "string",
    //         line2: "string",
    //         postal_code: "string",
    //         state: "string"
    //       },
    //       address_kana: {
    //         city: "string",
    //         country: "string",
    //         line1: "string",
    //         line2: "string",
    //         postal_code: "string",
    //         state: "string",
    //         town: "string"
    //       },
    //       address_kanji: {
    //         city: "string",
    //         country: "string",
    //         line1: "string",
    //         line2: "string",
    //         postal_code: "string",
    //         state: "string",
    //         town: "string"
    //       },
    //       directors_provided: true,
    //       executives_provided: true,
    //       name: "string",
    //       name_kana: "string",
    //       name_kanji: "string",
    //       owners_provided: true,
    //       ownership_declaration: { date: 0, ip: "string", user_agent: "string" },
    //       ownership_declaration_shown_and_signed: true,
    //       phone: "string",
    //       registration_number: "string",
    //       structure: "",
    //       tax_id: "string",
    //       tax_id_registrar: "string",
    //       vat_id: "string",
    //       verification: { document: { back: "string", front: "string" } }
    //     },
    //     individual: {
    //       address: {
    //         city: "string",
    //         country: "string",
    //         line1: "string",
    //         line2: "string",
    //         postal_code: "string",
    //         state: "string"
    //       },
    //       address_kana: {
    //         city: "string",
    //         country: "string",
    //         line1: "string",
    //         line2: "string",
    //         postal_code: "string",
    //         state: "string",
    //         town: "string"
    //       },
    //       address_kanji: {
    //         city: "string",
    //         country: "string",
    //         line1: "string",
    //         line2: "string",
    //         postal_code: "string",
    //         state: "string",
    //         town: "string"
    //       },
    //       dob: { day: 0, month: 0, year: 0 },
    //       email: "string",
    //       first_name: "string",
    //       first_name_kana: "string",
    //       first_name_kanji: "string",
    //       full_name_aliases: ["string"],
    //       gender: "string",
    //       id_number: "string",
    //       id_number_secondary: "string",
    //       last_name: "string",
    //       last_name_kana: "string",
    //       last_name_kanji: "string",
    //       maiden_name: "string",
    //       metadata: { property1: "string", property2: "string" },
    //       phone: "string",
    //       political_exposure: "existing",
    //       registered_address: {
    //         city: "string",
    //         country: "string",
    //         line1: "string",
    //         line2: "string",
    //         postal_code: "string",
    //         state: "string"
    //       },
    //       ssn_last_4: "string",
    //       verification: {
    //         additional_document: { back: "string", front: "string" },
    //         document: { back: "string", front: "string" }
    //       }
    //     },
    //     tos_shown_and_accepted: true
    //   },
    // bank_account: {
    //     account_holder_name: "string",
    //     account_holder_type: "company",
    //     account_number: "string",
    //     account_type: "checking",
    //     country: "string",
    //     currency: "string",
    //     routing_number: "string"
    //   },
    // card: {
    //     address_city: "string",
    //     address_country: "string",
    //     address_line1: "string",
    //     address_line2: "string",
    //     address_state: "string",
    //     address_zip: "string",
    //     currency: "string",
    //     cvc: "string",
    //     exp_month: "string",
    //     exp_year: "string",
    //     name: "string",
    //     number: "string"
    //   },
    // customer: "<string>",
    // cvc_update: { cvc: "string" },
    // expand: ["string"],
    // person: {
    //     address: {
    //       city: "string",
    //       country: "string",
    //       line1: "string",
    //       line2: "string",
    //       postal_code: "string",
    //       state: "string"
    //     },
    //     address_kana: {
    //       city: "string",
    //       country: "string",
    //       line1: "string",
    //       line2: "string",
    //       postal_code: "string",
    //       state: "string",
    //       town: "string"
    //     },
    //     address_kanji: {
    //       city: "string",
    //       country: "string",
    //       line1: "string",
    //       line2: "string",
    //       postal_code: "string",
    //       state: "string",
    //       town: "string"
    //     },
    //     dob: { day: 0, month: 0, year: 0 },
    //     documents: {
    //       company_authorization: { files: ["string"] },
    //       passport: { files: ["string"] },
    //       visa: { files: ["string"] }
    //     },
    //     email: "string",
    //     first_name: "string",
    //     first_name_kana: "string",
    //     first_name_kanji: "string",
    //     full_name_aliases: ["string"],
    //     gender: "string",
    //     id_number: "string",
    //     id_number_secondary: "string",
    //     last_name: "string",
    //     last_name_kana: "string",
    //     last_name_kanji: "string",
    //     maiden_name: "string",
    //     metadata: { property1: "string", property2: "string" },
    //     nationality: "string",
    //     phone: "string",
    //     political_exposure: "string",
    //     registered_address: {
    //       city: "string",
    //       country: "string",
    //       line1: "string",
    //       line2: "string",
    //       postal_code: "string",
    //       state: "string"
    //     },
    //     relationship: {
    //       director: true,
    //       executive: true,
    //       owner: true,
    //       percent_ownership: 0,
    //       representative: true,
    //       title: "string"
    //     },
    //     ssn_last_4: "string",
    //     verification: {
    //       additional_document: { back: "string", front: "string" },
    //       document: { back: "string", front: "string" }
    //     }
    //   },
    // pii: { id_number: "string" },
    // accountBusiness_type: "<string>",
    // accountCompanyAddressCity: "<string>",
    // accountCompanyAddressCountry: "<string>",
    // accountCompanyAddressLine1: "<string>",
    // accountCompanyAddressLine2: "<string>",
    // accountCompanyAddressPostal_code: "<string>",
    // accountCompanyAddressState: "<string>",
    // accountCompanyAddress_kanaCity: "<string>",
    // accountCompanyAddress_kanaCountry: "<string>",
    // accountCompanyAddress_kanaLine1: "<string>",
    // accountCompanyAddress_kanaLine2: "<string>",
    // accountCompanyAddress_kanaPostal_code: "<string>",
    // accountCompanyAddress_kanaState: "<string>",
    // accountCompanyAddress_kanaTown: "<string>",
    // accountCompanyAddress_kanjiCity: "<string>",
    // accountCompanyAddress_kanjiCountry: "<string>",
    // accountCompanyAddress_kanjiLine1: "<string>",
    // accountCompanyAddress_kanjiLine2: "<string>",
    // accountCompanyAddress_kanjiPostal_code: "<string>",
    // accountCompanyAddress_kanjiState: "<string>",
    // accountCompanyAddress_kanjiTown: "<string>",
    // accountCompanyDirectors_provided: "<boolean>",
    // accountCompanyExecutives_provided: "<boolean>",
    // accountCompanyName: "<string>",
    // accountCompanyName_kana: "<string>",
    // accountCompanyName_kanji: "<string>",
    // accountCompanyOwners_provided: "<boolean>",
    // accountCompanyOwnership_declarationDate: "<unix-time>",
    // accountCompanyOwnership_declarationIp: "<string>",
    // accountCompanyOwnership_declarationUser_agent: "<string>",
    // accountCompanyOwnership_declaration_shown_and_signed: "<boolean>",
    // accountCompanyPhone: "<string>",
    // accountCompanyRegistration_number: "<string>",
    // accountCompanyStructure: "<string>",
    // accountCompanyTax_id: "<string>",
    // accountCompanyTax_id_registrar: "<string>",
    // accountCompanyVat_id: "<string>",
    // accountCompanyVerificationDocumentBack: "<string>",
    // accountCompanyVerificationDocumentFront: "<string>",
    // accountIndividualAddressCity: "<string>",
    // accountIndividualAddressCountry: "<string>",
    // accountIndividualAddressLine1: "<string>",
    // accountIndividualAddressLine2: "<string>",
    // accountIndividualAddressPostal_code: "<string>",
    // accountIndividualAddressState: "<string>",
    // accountIndividualAddress_kanaCity: "<string>",
    // accountIndividualAddress_kanaCountry: "<string>",
    // accountIndividualAddress_kanaLine1: "<string>",
    // accountIndividualAddress_kanaLine2: "<string>",
    // accountIndividualAddress_kanaPostal_code: "<string>",
    // accountIndividualAddress_kanaState: "<string>",
    // accountIndividualAddress_kanaTown: "<string>",
    // accountIndividualAddress_kanjiCity: "<string>",
    // accountIndividualAddress_kanjiCountry: "<string>",
    // accountIndividualAddress_kanjiLine1: "<string>",
    // accountIndividualAddress_kanjiLine2: "<string>",
    // accountIndividualAddress_kanjiPostal_code: "<string>",
    // accountIndividualAddress_kanjiState: "<string>",
    // accountIndividualAddress_kanjiTown: "<string>",
    // accountIndividualDobDay: "<integer>",
    // accountIndividualDobMonth: "<integer>",
    // accountIndividualDobYear: "<integer>",
    // accountIndividualEmail: "<string>",
    // accountIndividualFirst_name: "<string>",
    // accountIndividualFirst_name_kana: "<string>",
    // accountIndividualFirst_name_kanji: "<string>",
    // accountIndividualFull_name_aliases0: "<string>",
    // accountIndividualFull_name_aliases1: "<string>",
    // accountIndividualGender: "<string>",
    // accountIndividualId_number: "<string>",
    // accountIndividualId_number_secondary: "<string>",
    // accountIndividualLast_name: "<string>",
    // accountIndividualLast_name_kana: "<string>",
    // accountIndividualLast_name_kanji: "<string>",
    // accountIndividualMaiden_name: "<string>",
    // accountIndividualMetadata: "<object>",
    // accountIndividualPhone: "<string>",
    // accountIndividualPolitical_exposure: "<string>",
    // accountIndividualRegistered_addressCity: "<string>",
    // accountIndividualRegistered_addressCountry: "<string>",
    // accountIndividualRegistered_addressLine1: "<string>",
    // accountIndividualRegistered_addressLine2: "<string>",
    // accountIndividualRegistered_addressPostal_code: "<string>",
    // accountIndividualRegistered_addressState: "<string>",
    // accountIndividualSsn_last_4: "<string>",
    // accountIndividualVerificationAdditional_documentBack: "<string>",
    // accountIndividualVerificationAdditional_documentFront: "<string>",
    // accountIndividualVerificationDocumentBack: "<string>",
    // accountIndividualVerificationDocumentFront: "<string>",
    // accountTos_shown_and_accepted: "<boolean>",
    // bank_accountAccount_number: "<string>",
    // bank_accountCountry: "<string>",
    // bank_accountAccount_holder_name: "<string>",
    // bank_accountAccount_holder_type: "<string>",
    // bank_accountAccount_type: "<string>",
    // bank_accountCurrency: "<string>",
    // bank_accountRouting_number: "<string>",
    // cardExp_month: "<string>",
    // cardExp_year: "<string>",
    // cardNumber: "<string>",
    // cardAddress_city: "<string>",
    // cardAddress_country: "<string>",
    // cardAddress_line1: "<string>",
    // cardAddress_line2: "<string>",
    // cardAddress_state: "<string>",
    // cardAddress_zip: "<string>",
    // cardCurrency: "<string>",
    // cardCvc: "<string>",
    // cardName: "<string>",
    // cvc_updateCvc: "<string>",
    // expand0: "<string>",
    // expand1: "<string>",
    // personAddressCity: "<string>",
    // personAddressCountry: "<string>",
    // personAddressLine1: "<string>",
    // personAddressLine2: "<string>",
    // personAddressPostal_code: "<string>",
    // personAddressState: "<string>",
    // personAddress_kanaCity: "<string>",
    // personAddress_kanaCountry: "<string>",
    // personAddress_kanaLine1: "<string>",
    // personAddress_kanaLine2: "<string>",
    // personAddress_kanaPostal_code: "<string>",
    // personAddress_kanaState: "<string>",
    // personAddress_kanaTown: "<string>",
    // personAddress_kanjiCity: "<string>",
    // personAddress_kanjiCountry: "<string>",
    // personAddress_kanjiLine1: "<string>",
    // personAddress_kanjiLine2: "<string>",
    // personAddress_kanjiPostal_code: "<string>",
    // personAddress_kanjiState: "<string>",
    // personAddress_kanjiTown: "<string>",
    // personDobDay: "<integer>",
    // personDobMonth: "<integer>",
    // personDobYear: "<integer>",
    // personDocumentsCompany_authorizationFiles0: "<string>",
    // personDocumentsCompany_authorizationFiles1: "<string>",
    // personDocumentsPassportFiles0: "<string>",
    // personDocumentsPassportFiles1: "<string>",
    // personDocumentsVisaFiles0: "<string>",
    // personDocumentsVisaFiles1: "<string>",
    // personEmail: "<string>",
    // personFirst_name: "<string>",
    // personFirst_name_kana: "<string>",
    // personFirst_name_kanji: "<string>",
    // personFull_name_aliases0: "<string>",
    // personFull_name_aliases1: "<string>",
    // personGender: "<string>",
    // personId_number: "<string>",
    // personId_number_secondary: "<string>",
    // personLast_name: "<string>",
    // personLast_name_kana: "<string>",
    // personLast_name_kanji: "<string>",
    // personMaiden_name: "<string>",
    // personMetadata: "<object>",
    // personNationality: "<string>",
    // personPhone: "<string>",
    // personPolitical_exposure: "<string>",
    // personRegistered_addressCity: "<string>",
    // personRegistered_addressCountry: "<string>",
    // personRegistered_addressLine1: "<string>",
    // personRegistered_addressLine2: "<string>",
    // personRegistered_addressPostal_code: "<string>",
    // personRegistered_addressState: "<string>",
    // personRelationshipDirector: "<boolean>",
    // personRelationshipExecutive: "<boolean>",
    // personRelationshipOwner: "<boolean>",
    // personRelationshipPercent_ownership: "<number>",
    // personRelationshipRepresentative: "<boolean>",
    // personRelationshipTitle: "<string>",
    // personSsn_last_4: "<string>",
    // personVerificationAdditional_documentBack: "<string>",
    // personVerificationAdditional_documentFront: "<string>",
    // personVerificationDocumentBack: "<string>",
    // personVerificationDocumentFront: "<string>",
    // piiId_number: "<string>",
  };
};
