const nodeInput = ({ $body, $headers, $env, $data }) => {
  return {
    BUILDABLE_STRIPE_SECRET_KEY: $env.BUILDABLE_STRIPE_SECRET_KEY, // Required
    account: "string", // Required
    person: "string", // Required

    // address: {
    //     city: "string",
    //     country: "string",
    //     line1: "string",
    //     line2: "string",
    //     postal_code: "string",
    //     state: "string"
    //   },
    // address_kana: {
    //     city: "string",
    //     country: "string",
    //     line1: "string",
    //     line2: "string",
    //     postal_code: "string",
    //     state: "string",
    //     town: "string"
    //   },
    // address_kanji: {
    //     city: "string",
    //     country: "string",
    //     line1: "string",
    //     line2: "string",
    //     postal_code: "string",
    //     state: "string",
    //     town: "string"
    //   },
    // dob: { day: 0, month: 0, year: 0 },
    // documents: {
    //     company_authorization: { files: ["string"] },
    //     passport: { files: ["string"] },
    //     visa: { files: ["string"] }
    //   },
    // email: "<string>",
    // expand: ["string"],
    // first_name: "<string>",
    // first_name_kana: "<string>",
    // first_name_kanji: "<string>",
    // full_name_aliases: ["string"],
    // gender: "<string>",
    // id_number: "<string>",
    // id_number_secondary: "<string>",
    // last_name: "<string>",
    // last_name_kana: "<string>",
    // last_name_kanji: "<string>",
    // maiden_name: "<string>",
    // metadata: { property1: "string", property2: "string" },
    // nationality: "<string>",
    // person_token: "<string>",
    // phone: "<string>",
    // political_exposure: "<string>",
    // registered_address: {
    //     city: "string",
    //     country: "string",
    //     line1: "string",
    //     line2: "string",
    //     postal_code: "string",
    //     state: "string"
    //   },
    // relationship: {
    //     director: true,
    //     executive: true,
    //     owner: true,
    //     percent_ownership: 0,
    //     representative: true,
    //     title: "string"
    //   },
    // ssn_last_4: "<string>",
    // verification: {
    //     additional_document: { back: "string", front: "string" },
    //     document: { back: "string", front: "string" }
    //   },
    // addressCity: "<string>",
    // addressCountry: "<string>",
    // addressLine1: "<string>",
    // addressLine2: "<string>",
    // addressPostal_code: "<string>",
    // addressState: "<string>",
    // address_kanaCity: "<string>",
    // address_kanaCountry: "<string>",
    // address_kanaLine1: "<string>",
    // address_kanaLine2: "<string>",
    // address_kanaPostal_code: "<string>",
    // address_kanaState: "<string>",
    // address_kanaTown: "<string>",
    // address_kanjiCity: "<string>",
    // address_kanjiCountry: "<string>",
    // address_kanjiLine1: "<string>",
    // address_kanjiLine2: "<string>",
    // address_kanjiPostal_code: "<string>",
    // address_kanjiState: "<string>",
    // address_kanjiTown: "<string>",
    // dobDay: "<integer>",
    // dobMonth: "<integer>",
    // dobYear: "<integer>",
    // documentsCompany_authorizationFiles0: "<string>",
    // documentsCompany_authorizationFiles1: "<string>",
    // documentsPassportFiles0: "<string>",
    // documentsPassportFiles1: "<string>",
    // documentsVisaFiles0: "<string>",
    // documentsVisaFiles1: "<string>",
    // expand0: "<string>",
    // expand1: "<string>",
    // full_name_aliases0: "<string>",
    // full_name_aliases1: "<string>",
    // registered_addressCity: "<string>",
    // registered_addressCountry: "<string>",
    // registered_addressLine1: "<string>",
    // registered_addressLine2: "<string>",
    // registered_addressPostal_code: "<string>",
    // registered_addressState: "<string>",
    // relationshipDirector: "<boolean>",
    // relationshipExecutive: "<boolean>",
    // relationshipOwner: "<boolean>",
    // relationshipPercent_ownership: "<number>",
    // relationshipRepresentative: "<boolean>",
    // relationshipTitle: "<string>",
    // verificationAdditional_documentBack: "<string>",
    // verificationAdditional_documentFront: "<string>",
    // verificationDocumentBack: "<string>",
    // verificationDocumentFront: "<string>",
  };
};
