const nodeInput = ({ $body, $headers, $env, $data }) => {
  return {
    BUILDABLE_STRIPE_SECRET_KEY: $env.BUILDABLE_STRIPE_SECRET_KEY, // Required
    account: "string", // Required

    // account_token: "<string>",
    // bank_account: {
    //     account_holder_name: "string",
    //     account_holder_type: "company",
    //     account_number: "string",
    //     account_type: "checking",
    //     country: "string",
    //     currency: "string",
    //     object: "bank_account",
    //     routing_number: "string"
    //   },
    // business_profile: {
    //     mcc: "string",
    //     name: "string",
    //     product_description: "string",
    //     support_address: {
    //       city: "string",
    //       country: "string",
    //       line1: "string",
    //       line2: "string",
    //       postal_code: "string",
    //       state: "string"
    //     },
    //     support_email: "string",
    //     support_phone: "string",
    //     support_url: "string",
    //     url: "string"
    //   },
    // business_type: "<string>",
    // capabilities: {
    //     acss_debit_payments: { requested: true },
    //     affirm_payments: { requested: true },
    //     afterpay_clearpay_payments: { requested: true },
    //     au_becs_debit_payments: { requested: true },
    //     bacs_debit_payments: { requested: true },
    //     bancontact_payments: { requested: true },
    //     bank_transfer_payments: { requested: true },
    //     blik_payments: { requested: true },
    //     boleto_payments: { requested: true },
    //     card_issuing: { requested: true },
    //     card_payments: { requested: true },
    //     cartes_bancaires_payments: { requested: true },
    //     eps_payments: { requested: true },
    //     fpx_payments: { requested: true },
    //     giropay_payments: { requested: true },
    //     grabpay_payments: { requested: true },
    //     ideal_payments: { requested: true },
    //     jcb_payments: { requested: true },
    //     klarna_payments: { requested: true },
    //     konbini_payments: { requested: true },
    //     legacy_payments: { requested: true },
    //     link_payments: { requested: true },
    //     oxxo_payments: { requested: true },
    //     p24_payments: { requested: true },
    //     paynow_payments: { requested: true },
    //     promptpay_payments: { requested: true },
    //     sepa_debit_payments: { requested: true },
    //     sofort_payments: { requested: true },
    //     tax_reporting_us_1099_k: { requested: true },
    //     tax_reporting_us_1099_misc: { requested: true },
    //     transfers: { requested: true },
    //     treasury: { requested: true },
    //     us_bank_account_ach_payments: { requested: true }
    //   },
    // company: {
    //     address: {
    //       city: "string",
    //       country: "string",
    //       line1: "string",
    //       line2: "string",
    //       postal_code: "string",
    //       state: "string"
    //     },
    //     address_kana: {
    //       city: "string",
    //       country: "string",
    //       line1: "string",
    //       line2: "string",
    //       postal_code: "string",
    //       state: "string",
    //       town: "string"
    //     },
    //     address_kanji: {
    //       city: "string",
    //       country: "string",
    //       line1: "string",
    //       line2: "string",
    //       postal_code: "string",
    //       state: "string",
    //       town: "string"
    //     },
    //     directors_provided: true,
    //     executives_provided: true,
    //     name: "string",
    //     name_kana: "string",
    //     name_kanji: "string",
    //     owners_provided: true,
    //     ownership_declaration: { date: 0, ip: "string", user_agent: "string" },
    //     phone: "string",
    //     registration_number: "string",
    //     structure: "",
    //     tax_id: "string",
    //     tax_id_registrar: "string",
    //     vat_id: "string",
    //     verification: { document: { back: "string", front: "string" } }
    //   },
    // default_currency: "<string>",
    // documents: {
    //     bank_account_ownership_verification: { files: ["string"] },
    //     company_license: { files: ["string"] },
    //     company_memorandum_of_association: { files: ["string"] },
    //     company_ministerial_decree: { files: ["string"] },
    //     company_registration_verification: { files: ["string"] },
    //     company_tax_id_verification: { files: ["string"] },
    //     proof_of_registration: { files: ["string"] }
    //   },
    // email: "<string>",
    // expand: ["string"],
    // external_account: "<string>",
    // individual: {
    //     address: {
    //       city: "string",
    //       country: "string",
    //       line1: "string",
    //       line2: "string",
    //       postal_code: "string",
    //       state: "string"
    //     },
    //     address_kana: {
    //       city: "string",
    //       country: "string",
    //       line1: "string",
    //       line2: "string",
    //       postal_code: "string",
    //       state: "string",
    //       town: "string"
    //     },
    //     address_kanji: {
    //       city: "string",
    //       country: "string",
    //       line1: "string",
    //       line2: "string",
    //       postal_code: "string",
    //       state: "string",
    //       town: "string"
    //     },
    //     dob: { day: 0, month: 0, year: 0 },
    //     email: "string",
    //     first_name: "string",
    //     first_name_kana: "string",
    //     first_name_kanji: "string",
    //     full_name_aliases: ["string"],
    //     gender: "string",
    //     id_number: "string",
    //     id_number_secondary: "string",
    //     last_name: "string",
    //     last_name_kana: "string",
    //     last_name_kanji: "string",
    //     maiden_name: "string",
    //     metadata: { property1: "string", property2: "string" },
    //     phone: "string",
    //     political_exposure: "existing",
    //     registered_address: {
    //       city: "string",
    //       country: "string",
    //       line1: "string",
    //       line2: "string",
    //       postal_code: "string",
    //       state: "string"
    //     },
    //     ssn_last_4: "string",
    //     verification: {
    //       additional_document: { back: "string", front: "string" },
    //       document: { back: "string", front: "string" }
    //     }
    //   },
    // metadata: { property1: "string", property2: "string" },
    // settings: {
    //     branding: {
    //       icon: "string",
    //       logo: "string",
    //       primary_color: "string",
    //       secondary_color: "string"
    //     },
    //     card_issuing: { tos_acceptance: { date: 0, ip: "string", user_agent: "string" } },
    //     card_payments: {
    //       decline_on: { avs_failure: true, cvc_failure: true },
    //       statement_descriptor_prefix: "string",
    //       statement_descriptor_prefix_kana: "string",
    //       statement_descriptor_prefix_kanji: "string"
    //     },
    //     payments: {
    //       statement_descriptor: "string",
    //       statement_descriptor_kana: "string",
    //       statement_descriptor_kanji: "string"
    //     },
    //     payouts: {
    //       debit_negative_balances: true,
    //       schedule: {
    //         delay_days: "minimum",
    //         interval: "daily",
    //         monthly_anchor: 0,
    //         weekly_anchor: "friday"
    //       },
    //       statement_descriptor: "string"
    //     },
    //     treasury: { tos_acceptance: { date: 0, ip: "string", user_agent: "string" } }
    //   },
    // tos_acceptance: { date: 0, ip: "string", service_agreement: "string", user_agent: "string" },
    // bank_accountAccount_number: "<string>",
    // bank_accountCountry: "<string>",
    // bank_accountAccount_holder_name: "<string>",
    // bank_accountAccount_holder_type: "<string>",
    // bank_accountAccount_type: "<string>",
    // bank_accountCurrency: "<string>",
    // bank_accountObject: "<string>",
    // bank_accountRouting_number: "<string>",
    // business_profileMcc: "<string>",
    // business_profileName: "<string>",
    // business_profileProduct_description: "<string>",
    // business_profileSupport_addressCity: "<string>",
    // business_profileSupport_addressCountry: "<string>",
    // business_profileSupport_addressLine1: "<string>",
    // business_profileSupport_addressLine2: "<string>",
    // business_profileSupport_addressPostal_code: "<string>",
    // business_profileSupport_addressState: "<string>",
    // business_profileSupport_email: "<string>",
    // business_profileSupport_phone: "<string>",
    // business_profileSupport_url: "<string>",
    // business_profileUrl: "<string>",
    // capabilitiesAcss_debit_paymentsRequested: "<boolean>",
    // capabilitiesAffirm_paymentsRequested: "<boolean>",
    // capabilitiesAfterpay_clearpay_paymentsRequested: "<boolean>",
    // capabilitiesAu_becs_debit_paymentsRequested: "<boolean>",
    // capabilitiesBacs_debit_paymentsRequested: "<boolean>",
    // capabilitiesBancontact_paymentsRequested: "<boolean>",
    // capabilitiesBank_transfer_paymentsRequested: "<boolean>",
    // capabilitiesBlik_paymentsRequested: "<boolean>",
    // capabilitiesBoleto_paymentsRequested: "<boolean>",
    // capabilitiesCard_issuingRequested: "<boolean>",
    // capabilitiesCard_paymentsRequested: "<boolean>",
    // capabilitiesCartes_bancaires_paymentsRequested: "<boolean>",
    // capabilitiesEps_paymentsRequested: "<boolean>",
    // capabilitiesFpx_paymentsRequested: "<boolean>",
    // capabilitiesGiropay_paymentsRequested: "<boolean>",
    // capabilitiesGrabpay_paymentsRequested: "<boolean>",
    // capabilitiesIdeal_paymentsRequested: "<boolean>",
    // capabilitiesJcb_paymentsRequested: "<boolean>",
    // capabilitiesKlarna_paymentsRequested: "<boolean>",
    // capabilitiesKonbini_paymentsRequested: "<boolean>",
    // capabilitiesLegacy_paymentsRequested: "<boolean>",
    // capabilitiesLink_paymentsRequested: "<boolean>",
    // capabilitiesOxxo_paymentsRequested: "<boolean>",
    // capabilitiesP24_paymentsRequested: "<boolean>",
    // capabilitiesPaynow_paymentsRequested: "<boolean>",
    // capabilitiesPromptpay_paymentsRequested: "<boolean>",
    // capabilitiesSepa_debit_paymentsRequested: "<boolean>",
    // capabilitiesSofort_paymentsRequested: "<boolean>",
    // capabilitiesTax_reporting_us_1099_kRequested: "<boolean>",
    // capabilitiesTax_reporting_us_1099_miscRequested: "<boolean>",
    // capabilitiesTransfersRequested: "<boolean>",
    // capabilitiesTreasuryRequested: "<boolean>",
    // capabilitiesUs_bank_account_ach_paymentsRequested: "<boolean>",
    // companyAddressCity: "<string>",
    // companyAddressCountry: "<string>",
    // companyAddressLine1: "<string>",
    // companyAddressLine2: "<string>",
    // companyAddressPostal_code: "<string>",
    // companyAddressState: "<string>",
    // companyAddress_kanaCity: "<string>",
    // companyAddress_kanaCountry: "<string>",
    // companyAddress_kanaLine1: "<string>",
    // companyAddress_kanaLine2: "<string>",
    // companyAddress_kanaPostal_code: "<string>",
    // companyAddress_kanaState: "<string>",
    // companyAddress_kanaTown: "<string>",
    // companyAddress_kanjiCity: "<string>",
    // companyAddress_kanjiCountry: "<string>",
    // companyAddress_kanjiLine1: "<string>",
    // companyAddress_kanjiLine2: "<string>",
    // companyAddress_kanjiPostal_code: "<string>",
    // companyAddress_kanjiState: "<string>",
    // companyAddress_kanjiTown: "<string>",
    // companyDirectors_provided: "<boolean>",
    // companyExecutives_provided: "<boolean>",
    // companyName: "<string>",
    // companyName_kana: "<string>",
    // companyName_kanji: "<string>",
    // companyOwners_provided: "<boolean>",
    // companyOwnership_declarationDate: "<unix-time>",
    // companyOwnership_declarationIp: "<string>",
    // companyOwnership_declarationUser_agent: "<string>",
    // companyPhone: "<string>",
    // companyRegistration_number: "<string>",
    // companyStructure: "<string>",
    // companyTax_id: "<string>",
    // companyTax_id_registrar: "<string>",
    // companyVat_id: "<string>",
    // companyVerificationDocumentBack: "<string>",
    // companyVerificationDocumentFront: "<string>",
    // documentsBank_account_ownership_verificationFiles0: "<string>",
    // documentsBank_account_ownership_verificationFiles1: "<string>",
    // documentsCompany_licenseFiles0: "<string>",
    // documentsCompany_licenseFiles1: "<string>",
    // documentsCompany_memorandum_of_associationFiles0: "<string>",
    // documentsCompany_memorandum_of_associationFiles1: "<string>",
    // documentsCompany_ministerial_decreeFiles0: "<string>",
    // documentsCompany_ministerial_decreeFiles1: "<string>",
    // documentsCompany_registration_verificationFiles0: "<string>",
    // documentsCompany_registration_verificationFiles1: "<string>",
    // documentsCompany_tax_id_verificationFiles0: "<string>",
    // documentsCompany_tax_id_verificationFiles1: "<string>",
    // documentsProof_of_registrationFiles0: "<string>",
    // documentsProof_of_registrationFiles1: "<string>",
    // expand0: "<string>",
    // expand1: "<string>",
    // individualAddressCity: "<string>",
    // individualAddressCountry: "<string>",
    // individualAddressLine1: "<string>",
    // individualAddressLine2: "<string>",
    // individualAddressPostal_code: "<string>",
    // individualAddressState: "<string>",
    // individualAddress_kanaCity: "<string>",
    // individualAddress_kanaCountry: "<string>",
    // individualAddress_kanaLine1: "<string>",
    // individualAddress_kanaLine2: "<string>",
    // individualAddress_kanaPostal_code: "<string>",
    // individualAddress_kanaState: "<string>",
    // individualAddress_kanaTown: "<string>",
    // individualAddress_kanjiCity: "<string>",
    // individualAddress_kanjiCountry: "<string>",
    // individualAddress_kanjiLine1: "<string>",
    // individualAddress_kanjiLine2: "<string>",
    // individualAddress_kanjiPostal_code: "<string>",
    // individualAddress_kanjiState: "<string>",
    // individualAddress_kanjiTown: "<string>",
    // individualDobDay: "<integer>",
    // individualDobMonth: "<integer>",
    // individualDobYear: "<integer>",
    // individualEmail: "<string>",
    // individualFirst_name: "<string>",
    // individualFirst_name_kana: "<string>",
    // individualFirst_name_kanji: "<string>",
    // individualFull_name_aliases0: "<string>",
    // individualFull_name_aliases1: "<string>",
    // individualGender: "<string>",
    // individualId_number: "<string>",
    // individualId_number_secondary: "<string>",
    // individualLast_name: "<string>",
    // individualLast_name_kana: "<string>",
    // individualLast_name_kanji: "<string>",
    // individualMaiden_name: "<string>",
    // individualMetadata: "<object>",
    // individualPhone: "<string>",
    // individualPolitical_exposure: "<string>",
    // individualRegistered_addressCity: "<string>",
    // individualRegistered_addressCountry: "<string>",
    // individualRegistered_addressLine1: "<string>",
    // individualRegistered_addressLine2: "<string>",
    // individualRegistered_addressPostal_code: "<string>",
    // individualRegistered_addressState: "<string>",
    // individualSsn_last_4: "<string>",
    // individualVerificationAdditional_documentBack: "<string>",
    // individualVerificationAdditional_documentFront: "<string>",
    // individualVerificationDocumentBack: "<string>",
    // individualVerificationDocumentFront: "<string>",
    // settingsBrandingIcon: "<string>",
    // settingsBrandingLogo: "<string>",
    // settingsBrandingPrimary_color: "<string>",
    // settingsBrandingSecondary_color: "<string>",
    // settingsCard_issuingTos_acceptanceDate: "<unix-time>",
    // settingsCard_issuingTos_acceptanceIp: "<string>",
    // settingsCard_issuingTos_acceptanceUser_agent: "<string>",
    // settingsCard_paymentsDecline_onAvs_failure: "<boolean>",
    // settingsCard_paymentsDecline_onCvc_failure: "<boolean>",
    // settingsCard_paymentsStatement_descriptor_prefix: "<string>",
    // settingsCard_paymentsStatement_descriptor_prefix_kana: "<string>",
    // settingsCard_paymentsStatement_descriptor_prefix_kanji: "<string>",
    // settingsPaymentsStatement_descriptor: "<string>",
    // settingsPaymentsStatement_descriptor_kana: "<string>",
    // settingsPaymentsStatement_descriptor_kanji: "<string>",
    // settingsPayoutsDebit_negative_balances: "<boolean>",
    // settingsPayoutsScheduleDelay_days: "<string>",
    // settingsPayoutsScheduleInterval: "<string>",
    // settingsPayoutsScheduleMonthly_anchor: "<integer>",
    // settingsPayoutsScheduleWeekly_anchor: "<string>",
    // settingsPayoutsStatement_descriptor: "<string>",
    // settingsTreasuryTos_acceptanceDate: "<unix-time>",
    // settingsTreasuryTos_acceptanceIp: "<string>",
    // settingsTreasuryTos_acceptanceUser_agent: "<string>",
    // tos_acceptanceDate: "<unix-time>",
    // tos_acceptanceIp: "<string>",
    // tos_acceptanceService_agreement: "<string>",
    // tos_acceptanceUser_agent: "<string>",
  };
};
