const nodeInput = ({ $body, $headers, $env, $data }) => {
  return {
    BUILDABLE_STRIPE_SECRET_KEY: $env.BUILDABLE_STRIPE_SECRET_KEY, // Required

    // attach_to_self: "<boolean>",
    // confirm: "<boolean>",
    // customer: "<string>",
    // description: "<string>",
    // expand: ["string"],
    // flow_directions: ["inbound"],
    // mandate_data: {
    //     customer_acceptance: {
    //       accepted_at: 0,
    //       offline: {},
    //       online: { ip_address: "string", user_agent: "string" },
    //       type: "offline"
    //     }
    //   },
    // metadata: { property1: "string", property2: "string" },
    // on_behalf_of: "<string>",
    // payment_method: "<string>",
    // payment_method_data: {
    //     acss_debit: {
    //       account_number: "string",
    //       institution_number: "string",
    //       transit_number: "string"
    //     },
    //     affirm: {},
    //     afterpay_clearpay: {},
    //     alipay: {},
    //     au_becs_debit: { account_number: "string", bsb_number: "string" },
    //     bacs_debit: { account_number: "string", sort_code: "string" },
    //     bancontact: {},
    //     billing_details: {
    //       address: {
    //         city: "string",
    //         country: "string",
    //         line1: "string",
    //         line2: "string",
    //         postal_code: "string",
    //         state: "string"
    //       },
    //       email: "string",
    //       name: "string",
    //       phone: "string"
    //     },
    //     blik: {},
    //     boleto: { tax_id: "string" },
    //     customer_balance: {},
    //     eps: { bank: "arzte_und_apotheker_bank" },
    //     fpx: { bank: "affin_bank" },
    //     giropay: {},
    //     grabpay: {},
    //     ideal: { bank: "abn_amro" },
    //     interac_present: {},
    //     klarna: { dob: { day: 0, month: 0, year: 0 } },
    //     konbini: {},
    //     link: {},
    //     metadata: { property1: "string", property2: "string" },
    //     oxxo: {},
    //     p24: { bank: "alior_bank" },
    //     paynow: {},
    //     promptpay: {},
    //     radar_options: { session: "string" },
    //     sepa_debit: { iban: "string" },
    //     sofort: { country: "AT" },
    //     type: "acss_debit",
    //     us_bank_account: {
    //       account_holder_type: "company",
    //       account_number: "string",
    //       account_type: "checking",
    //       financial_connections_account: "string",
    //       routing_number: "string"
    //     },
    //     wechat_pay: {}
    //   },
    // payment_method_options: {
    //     acss_debit: {
    //       currency: "cad",
    //       mandate_options: {
    //         custom_mandate_url: "string",
    //         default_for: ["invoice"],
    //         interval_description: "string",
    //         payment_schedule: "combined",
    //         transaction_type: "business"
    //       },
    //       verification_method: "automatic"
    //     },
    //     blik: { code: "string" },
    //     card: {
    //       mandate_options: {
    //         amount: 0,
    //         amount_type: "fixed",
    //         currency: "string",
    //         description: "string",
    //         end_date: 0,
    //         interval: "day",
    //         interval_count: 0,
    //         reference: "string",
    //         start_date: 0,
    //         supported_types: ["india"]
    //       },
    //       request_three_d_secure: "any"
    //     },
    //     link: { persistent_token: "string" },
    //     sepa_debit: { mandate_options: {} },
    //     us_bank_account: {
    //       financial_connections: { permissions: ["balances"], return_url: "string" },
    //       networks: { requested: ["ach"] },
    //       verification_method: "automatic"
    //     }
    //   },
    // payment_method_types: ["string"],
    // return_url: "<string>",
    // single_use: { amount: 0, currency: "string" },
    // usage: "<string>",
    // expand0: "<string>",
    // expand1: "<string>",
    // flow_directions0: "<string>",
    // flow_directions1: "<string>",
    // mandate_dataCustomer_acceptanceType: "<string>",
    // mandate_dataCustomer_acceptanceAccepted_at: "<unix-time>",
    // mandate_dataCustomer_acceptanceOnlineIp_address: "<string>",
    // mandate_dataCustomer_acceptanceOnlineUser_agent: "<string>",
    // payment_method_dataType: "<string>",
    // payment_method_dataAcss_debitAccount_number: "<string>",
    // payment_method_dataAcss_debitInstitution_number: "<string>",
    // payment_method_dataAcss_debitTransit_number: "<string>",
    // payment_method_dataAu_becs_debitAccount_number: "<string>",
    // payment_method_dataAu_becs_debitBsb_number: "<string>",
    // payment_method_dataBacs_debitAccount_number: "<string>",
    // payment_method_dataBacs_debitSort_code: "<string>",
    // payment_method_dataBilling_detailsAddressCity: "<string>",
    // payment_method_dataBilling_detailsAddressCountry: "<string>",
    // payment_method_dataBilling_detailsAddressLine1: "<string>",
    // payment_method_dataBilling_detailsAddressLine2: "<string>",
    // payment_method_dataBilling_detailsAddressPostal_code: "<string>",
    // payment_method_dataBilling_detailsAddressState: "<string>",
    // payment_method_dataBilling_detailsEmail: "<string>",
    // payment_method_dataBilling_detailsName: "<string>",
    // payment_method_dataBilling_detailsPhone: "<string>",
    // payment_method_dataBoletoTax_id: "<string>",
    // payment_method_dataEpsBank: "<string>",
    // payment_method_dataFpxBank: "<string>",
    // payment_method_dataIdealBank: "<string>",
    // payment_method_dataKlarnaDobDay: "<integer>",
    // payment_method_dataKlarnaDobMonth: "<integer>",
    // payment_method_dataKlarnaDobYear: "<integer>",
    // payment_method_dataMetadata: "<object>",
    // payment_method_dataP24Bank: "<string>",
    // payment_method_dataRadar_optionsSession: "<string>",
    // payment_method_dataSepa_debitIban: "<string>",
    // payment_method_dataSofortCountry: "<string>",
    // payment_method_dataUs_bank_accountAccount_holder_type: "<string>",
    // payment_method_dataUs_bank_accountAccount_number: "<string>",
    // payment_method_dataUs_bank_accountAccount_type: "<string>",
    // payment_method_dataUs_bank_accountFinancial_connections_account: "<string>",
    // payment_method_dataUs_bank_accountRouting_number: "<string>",
    // payment_method_optionsAcss_debitCurrency: "<string>",
    // payment_method_optionsAcss_debitMandate_optionsCustom_mandate_url: "<string>",
    // payment_method_optionsAcss_debitMandate_optionsDefault_for0: "<string>",
    // payment_method_optionsAcss_debitMandate_optionsDefault_for1: "<string>",
    // payment_method_optionsAcss_debitMandate_optionsInterval_description: "<string>",
    // payment_method_optionsAcss_debitMandate_optionsPayment_schedule: "<string>",
    // payment_method_optionsAcss_debitMandate_optionsTransaction_type: "<string>",
    // payment_method_optionsAcss_debitVerification_method: "<string>",
    // payment_method_optionsBlikCode: "<string>",
    // payment_method_optionsCardMandate_optionsAmount: "<integer>",
    // payment_method_optionsCardMandate_optionsAmount_type: "<string>",
    // payment_method_optionsCardMandate_optionsCurrency: "<string>",
    // payment_method_optionsCardMandate_optionsInterval: "<string>",
    // payment_method_optionsCardMandate_optionsReference: "<string>",
    // payment_method_optionsCardMandate_optionsStart_date: "<unix-time>",
    // payment_method_optionsCardMandate_optionsDescription: "<string>",
    // payment_method_optionsCardMandate_optionsEnd_date: "<unix-time>",
    // payment_method_optionsCardMandate_optionsInterval_count: "<integer>",
    // payment_method_optionsCardMandate_optionsSupported_types0: "<string>",
    // payment_method_optionsCardMandate_optionsSupported_types1: "<string>",
    // payment_method_optionsCardRequest_three_d_secure: "<string>",
    // payment_method_optionsLinkPersistent_token: "<string>",
    // payment_method_optionsUs_bank_accountFinancial_connectionsPermissions0: "<string>",
    // payment_method_optionsUs_bank_accountFinancial_connectionsPermissions1: "<string>",
    // payment_method_optionsUs_bank_accountFinancial_connectionsReturn_url: "<string>",
    // payment_method_optionsUs_bank_accountNetworksRequested0: "<string>",
    // payment_method_optionsUs_bank_accountNetworksRequested1: "<string>",
    // payment_method_optionsUs_bank_accountVerification_method: "<string>",
    // payment_method_types0: "<string>",
    // payment_method_types1: "<string>",
    // single_useAmount: "<integer>",
    // single_useCurrency: "<string>",
  };
};
