const nodeInput = ({ $body, $headers, $env, $data }) => {
  return {
    BUILDABLE_STRIPE_SECRET_KEY: $env.BUILDABLE_STRIPE_SECRET_KEY, // Required
    schedule: "string", // Required

    // default_settings: {
    //     application_fee_percent: 0,
    //     automatic_tax: { enabled: true },
    //     billing_cycle_anchor: "automatic",
    //     billing_thresholds: { amount_gte: 0, reset_billing_cycle_anchor: true },
    //     collection_method: "charge_automatically",
    //     default_payment_method: "string",
    //     invoice_settings: { days_until_due: 0 },
    //     transfer_data: { amount_percent: 0, destination: "string" }
    //   },
    // end_behavior: "<string>",
    // expand: ["string"],
    // metadata: { property1: "string", property2: "string" },
    // phases: [
    //     {
    //       add_invoice_items: [
    //         {
    //           price: "string",
    //           price_data: {
    //             currency: "string",
    //             product: "string",
    //             tax_behavior: "exclusive",
    //             unit_amount: 0,
    //             unit_amount_decimal: "string"
    //           },
    //           quantity: 0,
    //           tax_rates: ["string"]
    //         }
    //       ],
    //       application_fee_percent: 0,
    //       automatic_tax: { enabled: true },
    //       billing_cycle_anchor: "automatic",
    //       billing_thresholds: { amount_gte: 0, reset_billing_cycle_anchor: true },
    //       collection_method: "charge_automatically",
    //       coupon: "string",
    //       currency: "string",
    //       default_payment_method: "string",
    //       default_tax_rates: ["string"],
    //       end_date: 0,
    //       invoice_settings: { days_until_due: 0 },
    //       items: [
    //         {
    //           billing_thresholds: { usage_gte: 0 },
    //           price: "string",
    //           price_data: {
    //             currency: "string",
    //             product: "string",
    //             recurring: { interval: "day", interval_count: 0 },
    //             tax_behavior: "exclusive",
    //             unit_amount: 0,
    //             unit_amount_decimal: "string"
    //           },
    //           quantity: 0,
    //           tax_rates: ["string"]
    //         }
    //       ],
    //       iterations: 0,
    //       metadata: { property1: "string", property2: "string" },
    //       proration_behavior: "always_invoice",
    //       start_date: 0,
    //       transfer_data: { amount_percent: 0, destination: "string" },
    //       trial: true,
    //       trial_end: 0
    //     }
    //   ],
    // proration_behavior: "<string>",
    // default_settingsApplication_fee_percent: "<number>",
    // default_settingsAutomatic_taxEnabled: "<boolean>",
    // default_settingsBilling_cycle_anchor: "<string>",
    // default_settingsBilling_thresholdsAmount_gte: "<integer>",
    // default_settingsBilling_thresholdsReset_billing_cycle_anchor: "<boolean>",
    // default_settingsCollection_method: "<string>",
    // default_settingsDefault_payment_method: "<string>",
    // default_settingsInvoice_settingsDays_until_due: "<integer>",
    // default_settingsTransfer_dataDestination: "<string>",
    // default_settingsTransfer_dataAmount_percent: "<number>",
    // expand0: "<string>",
    // expand1: "<string>",
    // phases0Items0Billing_thresholdsUsage_gte: "<integer>",
    // phases0Items0Price: "<string>",
    // phases0Items0Price_dataCurrency: "<string>",
    // phases0Items0Price_dataProduct: "<string>",
    // phases0Items0Price_dataRecurringInterval: "<string>",
    // phases0Items0Price_dataRecurringInterval_count: "<integer>",
    // phases0Items0Price_dataTax_behavior: "<string>",
    // phases0Items0Price_dataUnit_amount: "<integer>",
    // phases0Items0Price_dataUnit_amount_decimal: "<decimal>",
    // phases0Items0Quantity: "<integer>",
    // phases0Items0Tax_rates0: "<string>",
    // phases0Items0Tax_rates1: "<string>",
    // phases0Items1Billing_thresholdsUsage_gte: "<integer>",
    // phases0Items1Price: "<string>",
    // phases0Items1Price_dataCurrency: "<string>",
    // phases0Items1Price_dataProduct: "<string>",
    // phases0Items1Price_dataRecurringInterval: "<string>",
    // phases0Items1Price_dataRecurringInterval_count: "<integer>",
    // phases0Items1Price_dataTax_behavior: "<string>",
    // phases0Items1Price_dataUnit_amount: "<integer>",
    // phases0Items1Price_dataUnit_amount_decimal: "<decimal>",
    // phases0Items1Quantity: "<integer>",
    // phases0Items1Tax_rates0: "<string>",
    // phases0Items1Tax_rates1: "<string>",
    // phases0Add_invoice_items0Price: "<string>",
    // phases0Add_invoice_items0Price_dataCurrency: "<string>",
    // phases0Add_invoice_items0Price_dataProduct: "<string>",
    // phases0Add_invoice_items0Price_dataTax_behavior: "<string>",
    // phases0Add_invoice_items0Price_dataUnit_amount: "<integer>",
    // phases0Add_invoice_items0Price_dataUnit_amount_decimal: "<decimal>",
    // phases0Add_invoice_items0Quantity: "<integer>",
    // phases0Add_invoice_items0Tax_rates0: "<string>",
    // phases0Add_invoice_items0Tax_rates1: "<string>",
    // phases0Add_invoice_items1Price: "<string>",
    // phases0Add_invoice_items1Price_dataCurrency: "<string>",
    // phases0Add_invoice_items1Price_dataProduct: "<string>",
    // phases0Add_invoice_items1Price_dataTax_behavior: "<string>",
    // phases0Add_invoice_items1Price_dataUnit_amount: "<integer>",
    // phases0Add_invoice_items1Price_dataUnit_amount_decimal: "<decimal>",
    // phases0Add_invoice_items1Quantity: "<integer>",
    // phases0Add_invoice_items1Tax_rates0: "<string>",
    // phases0Add_invoice_items1Tax_rates1: "<string>",
    // phases0Application_fee_percent: "<number>",
    // phases0Automatic_taxEnabled: "<boolean>",
    // phases0Billing_cycle_anchor: "<string>",
    // phases0Billing_thresholdsAmount_gte: "<integer>",
    // phases0Billing_thresholdsReset_billing_cycle_anchor: "<boolean>",
    // phases0Collection_method: "<string>",
    // phases0Coupon: "<string>",
    // phases0Currency: "<string>",
    // phases0Default_payment_method: "<string>",
    // phases0Default_tax_rates0: "<string>",
    // phases0Default_tax_rates1: "<string>",
    // phases0End_date: "<integer>",
    // phases0Invoice_settingsDays_until_due: "<integer>",
    // phases0Iterations: "<integer>",
    // phases0Metadata: "<object>",
    // phases0Proration_behavior: "<string>",
    // phases0Start_date: "<integer>",
    // phases0Transfer_dataDestination: "<string>",
    // phases0Transfer_dataAmount_percent: "<number>",
    // phases0Trial: "<boolean>",
    // phases0Trial_end: "<integer>",
    // phases1Items0Billing_thresholdsUsage_gte: "<integer>",
    // phases1Items0Price: "<string>",
    // phases1Items0Price_dataCurrency: "<string>",
    // phases1Items0Price_dataProduct: "<string>",
    // phases1Items0Price_dataRecurringInterval: "<string>",
    // phases1Items0Price_dataRecurringInterval_count: "<integer>",
    // phases1Items0Price_dataTax_behavior: "<string>",
    // phases1Items0Price_dataUnit_amount: "<integer>",
    // phases1Items0Price_dataUnit_amount_decimal: "<decimal>",
    // phases1Items0Quantity: "<integer>",
    // phases1Items0Tax_rates0: "<string>",
    // phases1Items0Tax_rates1: "<string>",
    // phases1Items1Billing_thresholdsUsage_gte: "<integer>",
    // phases1Items1Price: "<string>",
    // phases1Items1Price_dataCurrency: "<string>",
    // phases1Items1Price_dataProduct: "<string>",
    // phases1Items1Price_dataRecurringInterval: "<string>",
    // phases1Items1Price_dataRecurringInterval_count: "<integer>",
    // phases1Items1Price_dataTax_behavior: "<string>",
    // phases1Items1Price_dataUnit_amount: "<integer>",
    // phases1Items1Price_dataUnit_amount_decimal: "<decimal>",
    // phases1Items1Quantity: "<integer>",
    // phases1Items1Tax_rates0: "<string>",
    // phases1Items1Tax_rates1: "<string>",
    // phases1Add_invoice_items0Price: "<string>",
    // phases1Add_invoice_items0Price_dataCurrency: "<string>",
    // phases1Add_invoice_items0Price_dataProduct: "<string>",
    // phases1Add_invoice_items0Price_dataTax_behavior: "<string>",
    // phases1Add_invoice_items0Price_dataUnit_amount: "<integer>",
    // phases1Add_invoice_items0Price_dataUnit_amount_decimal: "<decimal>",
    // phases1Add_invoice_items0Quantity: "<integer>",
    // phases1Add_invoice_items0Tax_rates0: "<string>",
    // phases1Add_invoice_items0Tax_rates1: "<string>",
    // phases1Add_invoice_items1Price: "<string>",
    // phases1Add_invoice_items1Price_dataCurrency: "<string>",
    // phases1Add_invoice_items1Price_dataProduct: "<string>",
    // phases1Add_invoice_items1Price_dataTax_behavior: "<string>",
    // phases1Add_invoice_items1Price_dataUnit_amount: "<integer>",
    // phases1Add_invoice_items1Price_dataUnit_amount_decimal: "<decimal>",
    // phases1Add_invoice_items1Quantity: "<integer>",
    // phases1Add_invoice_items1Tax_rates0: "<string>",
    // phases1Add_invoice_items1Tax_rates1: "<string>",
    // phases1Application_fee_percent: "<number>",
    // phases1Automatic_taxEnabled: "<boolean>",
    // phases1Billing_cycle_anchor: "<string>",
    // phases1Billing_thresholdsAmount_gte: "<integer>",
    // phases1Billing_thresholdsReset_billing_cycle_anchor: "<boolean>",
    // phases1Collection_method: "<string>",
    // phases1Coupon: "<string>",
    // phases1Currency: "<string>",
    // phases1Default_payment_method: "<string>",
    // phases1Default_tax_rates0: "<string>",
    // phases1Default_tax_rates1: "<string>",
    // phases1End_date: "<integer>",
    // phases1Invoice_settingsDays_until_due: "<integer>",
    // phases1Iterations: "<integer>",
    // phases1Metadata: "<object>",
    // phases1Proration_behavior: "<string>",
    // phases1Start_date: "<integer>",
    // phases1Transfer_dataDestination: "<string>",
    // phases1Transfer_dataAmount_percent: "<number>",
    // phases1Trial: "<boolean>",
    // phases1Trial_end: "<integer>",
  };
};
