const nodeInput = ({ $body, $headers, $env, $data }) => {
  return {
    BUILDABLE_STRIPE_SECRET_KEY: $env.BUILDABLE_STRIPE_SECRET_KEY, // Required

    // application_fee_amount: 0,
    // application_fee_percent: 0,
    // automatic_tax: { enabled: true },
    // collection_method: "<string>",
    // customer: "<string>",
    // default_tax_rates: ["string"],
    // description: "<string>",
    // discounts: [{ coupon: "string", discount: "string" }],
    // expand: ["string"],
    // expires_at: "<unix-time>",
    // footer: "<string>",
    // from_quote: { is_revision: true, quote: "string" },
    // header: "<string>",
    // invoice_settings: { days_until_due: 0 },
    // line_items: [
    //     {
    //       price: "string",
    //       price_data: {
    //         currency: "string",
    //         product: "string",
    //         recurring: { interval: "day", interval_count: 0 },
    //         tax_behavior: "exclusive",
    //         unit_amount: 0,
    //         unit_amount_decimal: "string"
    //       },
    //       quantity: 0,
    //       tax_rates: ["string"]
    //     }
    //   ],
    // metadata: { property1: "string", property2: "string" },
    // on_behalf_of: "string",
    // subscription_data: { effective_date: "current_period_end", trial_period_days: 0 },
    // test_clock: "<string>",
    // transfer_data: { amount: 0, amount_percent: 0, destination: "string" },
    // automatic_taxEnabled: "<boolean>",
    // default_tax_rates0: "<string>",
    // default_tax_rates1: "<string>",
    // discounts0Coupon: "<string>",
    // discounts0Discount: "<string>",
    // discounts1Coupon: "<string>",
    // discounts1Discount: "<string>",
    // expand0: "<string>",
    // expand1: "<string>",
    // from_quoteQuote: "<string>",
    // from_quoteIs_revision: "<boolean>",
    // invoice_settingsDays_until_due: "<integer>",
    // line_items0Price: "<string>",
    // line_items0Price_dataCurrency: "<string>",
    // line_items0Price_dataProduct: "<string>",
    // line_items0Price_dataRecurringInterval: "<string>",
    // line_items0Price_dataRecurringInterval_count: "<integer>",
    // line_items0Price_dataTax_behavior: "<string>",
    // line_items0Price_dataUnit_amount: "<integer>",
    // line_items0Price_dataUnit_amount_decimal: "<decimal>",
    // line_items0Quantity: "<integer>",
    // line_items0Tax_rates0: "<string>",
    // line_items0Tax_rates1: "<string>",
    // line_items1Price: "<string>",
    // line_items1Price_dataCurrency: "<string>",
    // line_items1Price_dataProduct: "<string>",
    // line_items1Price_dataRecurringInterval: "<string>",
    // line_items1Price_dataRecurringInterval_count: "<integer>",
    // line_items1Price_dataTax_behavior: "<string>",
    // line_items1Price_dataUnit_amount: "<integer>",
    // line_items1Price_dataUnit_amount_decimal: "<decimal>",
    // line_items1Quantity: "<integer>",
    // line_items1Tax_rates0: "<string>",
    // line_items1Tax_rates1: "<string>",
    // subscription_dataEffective_date: "<string>",
    // subscription_dataTrial_period_days: "<integer>",
    // transfer_dataDestination: "<string>",
    // transfer_dataAmount: "<integer>",
    // transfer_dataAmount_percent: "<number>",
  };
};
