const nodeInput = ({ $body, $headers, $env, $data }) => {
  return {
    BUILDABLE_STRIPE_SECRET_KEY: $env.BUILDABLE_STRIPE_SECRET_KEY, // Required
    intent: "string", // Required

    // capture_method: "<string>",
    // client_secret: "<string>",
    // error_on_requires_action: "<boolean>",
    // expand: ["string"],
    // mandate: "<string>",
    // mandate_data: {
    //     customer_acceptance: {
    //       accepted_at: 0,
    //       offline: {},
    //       online: { ip_address: "string", user_agent: "string" },
    //       type: "offline"
    //     }
    //   },
    // off_session: true,
    // payment_method: "<string>",
    // payment_method_data: {
    //     acss_debit: {
    //       account_number: "string",
    //       institution_number: "string",
    //       transit_number: "string"
    //     },
    //     affirm: {},
    //     afterpay_clearpay: {},
    //     alipay: {},
    //     au_becs_debit: { account_number: "string", bsb_number: "string" },
    //     bacs_debit: { account_number: "string", sort_code: "string" },
    //     bancontact: {},
    //     billing_details: {
    //       address: {
    //         city: "string",
    //         country: "string",
    //         line1: "string",
    //         line2: "string",
    //         postal_code: "string",
    //         state: "string"
    //       },
    //       email: "string",
    //       name: "string",
    //       phone: "string"
    //     },
    //     blik: {},
    //     boleto: { tax_id: "string" },
    //     customer_balance: {},
    //     eps: { bank: "arzte_und_apotheker_bank" },
    //     fpx: { bank: "affin_bank" },
    //     giropay: {},
    //     grabpay: {},
    //     ideal: { bank: "abn_amro" },
    //     interac_present: {},
    //     klarna: { dob: { day: 0, month: 0, year: 0 } },
    //     konbini: {},
    //     link: {},
    //     metadata: { property1: "string", property2: "string" },
    //     oxxo: {},
    //     p24: { bank: "alior_bank" },
    //     paynow: {},
    //     promptpay: {},
    //     radar_options: { session: "string" },
    //     sepa_debit: { iban: "string" },
    //     sofort: { country: "AT" },
    //     type: "acss_debit",
    //     us_bank_account: {
    //       account_holder_type: "company",
    //       account_number: "string",
    //       account_type: "checking",
    //       financial_connections_account: "string",
    //       routing_number: "string"
    //     },
    //     wechat_pay: {}
    //   },
    // payment_method_options: {
    //     acss_debit: {
    //       mandate_options: {
    //         custom_mandate_url: "string",
    //         interval_description: "string",
    //         payment_schedule: "combined",
    //         transaction_type: "business"
    //       },
    //       setup_future_usage: "",
    //       verification_method: "automatic"
    //     },
    //     affirm: { capture_method: "", setup_future_usage: "none" },
    //     afterpay_clearpay: { capture_method: "", reference: "string", setup_future_usage: "none" },
    //     alipay: { setup_future_usage: "" },
    //     au_becs_debit: { setup_future_usage: "" },
    //     bacs_debit: { setup_future_usage: "" },
    //     bancontact: { preferred_language: "de", setup_future_usage: "" },
    //     blik: { code: "string" },
    //     boleto: { expires_after_days: 0, setup_future_usage: "" },
    //     card: {
    //       capture_method: "",
    //       cvc_token: "string",
    //       installments: { enabled: true, plan: { count: 0, interval: "month", type: "fixed_count" } },
    //       mandate_options: {
    //         amount: 0,
    //         amount_type: "fixed",
    //         description: "string",
    //         end_date: 0,
    //         interval: "day",
    //         interval_count: 0,
    //         reference: "string",
    //         start_date: 0,
    //         supported_types: ["india"]
    //       },
    //       network: "amex",
    //       request_three_d_secure: "any",
    //       setup_future_usage: "",
    //       statement_descriptor_suffix_kana: "string",
    //       statement_descriptor_suffix_kanji: "string"
    //     },
    //     card_present: {
    //       request_extended_authorization: true,
    //       request_incremental_authorization_support: true
    //     },
    //     customer_balance: {
    //       bank_transfer: {
    //         eu_bank_transfer: { country: "string" },
    //         requested_address_types: ["iban"],
    //         type: "eu_bank_transfer"
    //       },
    //       funding_type: "bank_transfer",
    //       setup_future_usage: "none"
    //     },
    //     eps: { setup_future_usage: "none" },
    //     fpx: { setup_future_usage: "none" },
    //     giropay: { setup_future_usage: "none" },
    //     grabpay: { setup_future_usage: "none" },
    //     ideal: { setup_future_usage: "" },
    //     interac_present: {},
    //     klarna: { capture_method: "", preferred_locale: "da-DK", setup_future_usage: "none" },
    //     konbini: {
    //       confirmation_number: "string",
    //       expires_after_days: 0,
    //       expires_at: 0,
    //       product_description: "string",
    //       setup_future_usage: "none"
    //     },
    //     link: { capture_method: "", persistent_token: "string", setup_future_usage: "" },
    //     oxxo: { expires_after_days: 0, setup_future_usage: "none" },
    //     p24: { setup_future_usage: "none", tos_shown_and_accepted: true },
    //     paynow: { setup_future_usage: "none" },
    //     promptpay: { setup_future_usage: "none" },
    //     sepa_debit: { mandate_options: {}, setup_future_usage: "" },
    //     sofort: { preferred_language: "", setup_future_usage: "" },
    //     us_bank_account: {
    //       financial_connections: { permissions: ["balances"], return_url: "string" },
    //       networks: { requested: ["ach"] },
    //       setup_future_usage: "",
    //       verification_method: "automatic"
    //     },
    //     wechat_pay: { app_id: "string", client: "android", setup_future_usage: "none" }
    //   },
    // payment_method_types: ["string"],
    // radar_options: { session: "string" },
    // receipt_email: "string",
    // return_url: "<string>",
    // setup_future_usage: "<string>",
    // shipping: {
    //     address: {
    //       city: "string",
    //       country: "string",
    //       line1: "string",
    //       line2: "string",
    //       postal_code: "string",
    //       state: "string"
    //     },
    //     carrier: "string",
    //     name: "string",
    //     phone: "string",
    //     tracking_number: "string"
    //   },
    // use_stripe_sdk: "<boolean>",
    // expand0: "<string>",
    // expand1: "<string>",
    // mandate_dataCustomer_acceptanceType: "<string>",
    // mandate_dataCustomer_acceptanceAccepted_at: "<unix-time>",
    // mandate_dataCustomer_acceptanceOnlineIp_address: "<string>",
    // mandate_dataCustomer_acceptanceOnlineUser_agent: "<string>",
    // payment_method_dataType: "<string>",
    // payment_method_dataAcss_debitAccount_number: "<string>",
    // payment_method_dataAcss_debitInstitution_number: "<string>",
    // payment_method_dataAcss_debitTransit_number: "<string>",
    // payment_method_dataAu_becs_debitAccount_number: "<string>",
    // payment_method_dataAu_becs_debitBsb_number: "<string>",
    // payment_method_dataBacs_debitAccount_number: "<string>",
    // payment_method_dataBacs_debitSort_code: "<string>",
    // payment_method_dataBilling_detailsAddressCity: "<string>",
    // payment_method_dataBilling_detailsAddressCountry: "<string>",
    // payment_method_dataBilling_detailsAddressLine1: "<string>",
    // payment_method_dataBilling_detailsAddressLine2: "<string>",
    // payment_method_dataBilling_detailsAddressPostal_code: "<string>",
    // payment_method_dataBilling_detailsAddressState: "<string>",
    // payment_method_dataBilling_detailsEmail: "<string>",
    // payment_method_dataBilling_detailsName: "<string>",
    // payment_method_dataBilling_detailsPhone: "<string>",
    // payment_method_dataBoletoTax_id: "<string>",
    // payment_method_dataEpsBank: "<string>",
    // payment_method_dataFpxBank: "<string>",
    // payment_method_dataIdealBank: "<string>",
    // payment_method_dataKlarnaDobDay: "<integer>",
    // payment_method_dataKlarnaDobMonth: "<integer>",
    // payment_method_dataKlarnaDobYear: "<integer>",
    // payment_method_dataMetadata: "<object>",
    // payment_method_dataP24Bank: "<string>",
    // payment_method_dataRadar_optionsSession: "<string>",
    // payment_method_dataSepa_debitIban: "<string>",
    // payment_method_dataSofortCountry: "<string>",
    // payment_method_dataUs_bank_accountAccount_holder_type: "<string>",
    // payment_method_dataUs_bank_accountAccount_number: "<string>",
    // payment_method_dataUs_bank_accountAccount_type: "<string>",
    // payment_method_dataUs_bank_accountFinancial_connections_account: "<string>",
    // payment_method_dataUs_bank_accountRouting_number: "<string>",
    // payment_method_optionsAcss_debitMandate_optionsCustom_mandate_url: "<string>",
    // payment_method_optionsAcss_debitMandate_optionsInterval_description: "<string>",
    // payment_method_optionsAcss_debitMandate_optionsPayment_schedule: "<string>",
    // payment_method_optionsAcss_debitMandate_optionsTransaction_type: "<string>",
    // payment_method_optionsAcss_debitSetup_future_usage: "<string>",
    // payment_method_optionsAcss_debitVerification_method: "<string>",
    // payment_method_optionsAffirmCapture_method: "<string>",
    // payment_method_optionsAffirmSetup_future_usage: "<string>",
    // payment_method_optionsAfterpay_clearpayCapture_method: "<string>",
    // payment_method_optionsAfterpay_clearpayReference: "<string>",
    // payment_method_optionsAfterpay_clearpaySetup_future_usage: "<string>",
    // payment_method_optionsAlipaySetup_future_usage: "<string>",
    // payment_method_optionsAu_becs_debitSetup_future_usage: "<string>",
    // payment_method_optionsBacs_debitSetup_future_usage: "<string>",
    // payment_method_optionsBancontactPreferred_language: "<string>",
    // payment_method_optionsBancontactSetup_future_usage: "<string>",
    // payment_method_optionsBlikCode: "<string>",
    // payment_method_optionsBoletoExpires_after_days: "<integer>",
    // payment_method_optionsBoletoSetup_future_usage: "<string>",
    // payment_method_optionsCardCapture_method: "<string>",
    // payment_method_optionsCardCvc_token: "<string>",
    // payment_method_optionsCardInstallmentsEnabled: "<boolean>",
    // payment_method_optionsCardInstallmentsPlanCount: "<integer>",
    // payment_method_optionsCardInstallmentsPlanInterval: "<string>",
    // payment_method_optionsCardInstallmentsPlanType: "<string>",
    // payment_method_optionsCardMandate_optionsAmount: "<integer>",
    // payment_method_optionsCardMandate_optionsAmount_type: "<string>",
    // payment_method_optionsCardMandate_optionsInterval: "<string>",
    // payment_method_optionsCardMandate_optionsReference: "<string>",
    // payment_method_optionsCardMandate_optionsStart_date: "<unix-time>",
    // payment_method_optionsCardMandate_optionsDescription: "<string>",
    // payment_method_optionsCardMandate_optionsEnd_date: "<unix-time>",
    // payment_method_optionsCardMandate_optionsInterval_count: "<integer>",
    // payment_method_optionsCardMandate_optionsSupported_types0: "<string>",
    // payment_method_optionsCardMandate_optionsSupported_types1: "<string>",
    // payment_method_optionsCardNetwork: "<string>",
    // payment_method_optionsCardRequest_three_d_secure: "<string>",
    // payment_method_optionsCardSetup_future_usage: "<string>",
    // payment_method_optionsCardStatement_descriptor_suffix_kana: "<string>",
    // payment_method_optionsCardStatement_descriptor_suffix_kanji: "<string>",
    // payment_method_optionsCard_presentRequest_extended_authorization: "<boolean>",
    // payment_method_optionsCard_presentRequest_incremental_authorization_support: "<boolean>",
    // payment_method_optionsCustomer_balanceBank_transferType: "<string>",
    // payment_method_optionsCustomer_balanceBank_transferEu_bank_transferCountry: "<string>",
    // payment_method_optionsCustomer_balanceBank_transferRequested_address_types0: "<string>",
    // payment_method_optionsCustomer_balanceBank_transferRequested_address_types1: "<string>",
    // payment_method_optionsCustomer_balanceFunding_type: "<string>",
    // payment_method_optionsCustomer_balanceSetup_future_usage: "<string>",
    // payment_method_optionsEpsSetup_future_usage: "<string>",
    // payment_method_optionsFpxSetup_future_usage: "<string>",
    // payment_method_optionsGiropaySetup_future_usage: "<string>",
    // payment_method_optionsGrabpaySetup_future_usage: "<string>",
    // payment_method_optionsIdealSetup_future_usage: "<string>",
    // payment_method_optionsKlarnaCapture_method: "<string>",
    // payment_method_optionsKlarnaPreferred_locale: "<string>",
    // payment_method_optionsKlarnaSetup_future_usage: "<string>",
    // payment_method_optionsKonbiniConfirmation_number: "<string>",
    // payment_method_optionsKonbiniExpires_after_days: "<integer>",
    // payment_method_optionsKonbiniExpires_at: "<unix-time>",
    // payment_method_optionsKonbiniProduct_description: "<string>",
    // payment_method_optionsKonbiniSetup_future_usage: "<string>",
    // payment_method_optionsLinkCapture_method: "<string>",
    // payment_method_optionsLinkPersistent_token: "<string>",
    // payment_method_optionsLinkSetup_future_usage: "<string>",
    // payment_method_optionsOxxoExpires_after_days: "<integer>",
    // payment_method_optionsOxxoSetup_future_usage: "<string>",
    // payment_method_optionsP24Setup_future_usage: "<string>",
    // payment_method_optionsP24Tos_shown_and_accepted: "<boolean>",
    // payment_method_optionsPaynowSetup_future_usage: "<string>",
    // payment_method_optionsPromptpaySetup_future_usage: "<string>",
    // payment_method_optionsSepa_debitSetup_future_usage: "<string>",
    // payment_method_optionsSofortPreferred_language: "<string>",
    // payment_method_optionsSofortSetup_future_usage: "<string>",
    // payment_method_optionsUs_bank_accountFinancial_connectionsPermissions0: "<string>",
    // payment_method_optionsUs_bank_accountFinancial_connectionsPermissions1: "<string>",
    // payment_method_optionsUs_bank_accountFinancial_connectionsReturn_url: "<string>",
    // payment_method_optionsUs_bank_accountNetworksRequested0: "<string>",
    // payment_method_optionsUs_bank_accountNetworksRequested1: "<string>",
    // payment_method_optionsUs_bank_accountSetup_future_usage: "<string>",
    // payment_method_optionsUs_bank_accountVerification_method: "<string>",
    // payment_method_optionsWechat_payClient: "<string>",
    // payment_method_optionsWechat_payApp_id: "<string>",
    // payment_method_optionsWechat_paySetup_future_usage: "<string>",
    // payment_method_types0: "<string>",
    // payment_method_types1: "<string>",
    // radar_optionsSession: "<string>",
    // shippingAddressCity: "<string>",
    // shippingAddressCountry: "<string>",
    // shippingAddressLine1: "<string>",
    // shippingAddressLine2: "<string>",
    // shippingAddressPostal_code: "<string>",
    // shippingAddressState: "<string>",
    // shippingName: "<string>",
    // shippingCarrier: "<string>",
    // shippingPhone: "<string>",
    // shippingTracking_number: "<string>",
  };
};
